export interface LocationContent {
  slug: string;
  name: string;
  state: string;
  h1: string;
  metaDescription: string;
  coordinates: { lat: number; lng: number };
  heroDescription: string;
  localProblems: string[];
  whyChooseUs: string[];
  neighborhoods: string[];
  serviceHighlights: string[];
  responseTime: string;
}

export const LOCATION_CONTENT: { [key: string]: LocationContent } = {
  'cave-spring': {
    slug: 'cave-spring',
    name: 'Cave Spring',
    state: 'VA',
    h1: 'Emergency Plumbing in Cave Spring, VA - 24/7 Local Service',
    metaDescription: 'Cave Spring plumber providing 24/7 emergency service, water heater repair, drain cleaning, and leak detection. Fast, local, licensed master plumber. Call now!',
    coordinates: { lat: 37.2296, lng: -79.9842 },
    heroDescription: 'Serving Cave Spring with fast, reliable plumbing services. Our local team responds quickly to emergencies and provides expert plumbing solutions for homes and businesses.',
    localProblems: [
      'Winter freeze issues causing burst pipes in Cave Spring Corners',
      'Hard water problems affecting fixtures and appliances',
      'Sewer line issues from tree roots in older neighborhoods',
      'Water heater failures during cold snaps',
      'Clogged drains from Hunting Hills area developments',
      'Aging plumbing in established Cave Spring homes',
    ],
    whyChooseUs: [
      'Based locally - fastest response times in Cave Spring',
      'Familiar with Cave Spring homes and common issues',
      'Same-day service available for Cave Spring residents',
      '16+ years serving the Cave Spring community',
      'Licensed master plumber with local expertise',
      'Upfront pricing - no surprises for Cave Spring customers',
    ],
    neighborhoods: [
      'Cave Spring Corners',
      'Hunting Hills',
      'Cave Spring High School area',
      'Ogden Road community',
      'Grandin Road extension',
    ],
    serviceHighlights: [
      'Emergency plumbing repair',
      'Water heater installation and repair',
      'Drain cleaning and sewer services',
      'Leak detection and pipe repair',
      'Toilet and fixture repairs',
      'Sump pump installation',
      'Bathroom and kitchen plumbing',
      'Monthly home protection plans',
    ],
    responseTime: 'Average response time in Cave Spring: 30-45 minutes for emergencies',
  },
  'roanoke': {
    slug: 'roanoke',
    name: 'Roanoke',
    state: 'VA',
    h1: 'Emergency Plumbing in Roanoke, VA - 24/7 Fast Response',
    metaDescription: 'Roanoke plumber specializing in older homes (1950s-1980s). 24/7 emergency service, pipe repairs, water heaters, drain cleaning. Licensed master plumber. Call now!',
    coordinates: { lat: 37.2710, lng: -79.9414 },
    heroDescription: 'Expert plumbing for Roanoke homes, specializing in older 1950s-1980s builds with aging pipes and unique plumbing challenges. Fast emergency response across all Roanoke neighborhoods.',
    localProblems: [
      'Aging pipes in 1950s-1980s Roanoke homes breaking down',
      'Cast iron pipe corrosion in Old Southwest homes',
      'Galvanized pipe replacement needed in South Roanoke',
      'Winter freeze damage on exposed pipes',
      'Sewer line bellies and breaks from settling foundations',
      'Water pressure issues from old city water lines',
      'Outdated fixtures and plumbing in historic Roanoke properties',
    ],
    whyChooseUs: [
      'Specialist in older Roanoke homes (1950s-1980s builds)',
      'Experience with historic Old Southwest plumbing',
      'Expert pipe fitter for repiping older homes',
      'Fast response across all Roanoke neighborhoods',
      '16+ years working on Roanoke properties',
      'Honest assessments for aging plumbing systems',
    ],
    neighborhoods: [
      'Old Southwest',
      'South Roanoke',
      'Grandin Village',
      'Wasena',
      'Belmont',
      'Garden City',
      'Raleigh Court',
    ],
    serviceHighlights: [
      'Repiping for older homes',
      'Emergency pipe repair',
      'Water heater replacement',
      'Sewer line repair and replacement',
      'Leak detection in older plumbing',
      'Cast iron pipe replacement',
      'Galvanized pipe upgrades',
      'Historic home plumbing expertise',
    ],
    responseTime: 'Average response time in Roanoke: 30-45 minutes for emergencies',
  },
  'salem': {
    slug: 'salem',
    name: 'Salem',
    state: 'VA',
    h1: 'Emergency Plumbing in Salem, VA - 24/7 Local Service',
    metaDescription: 'Salem plumber providing 24/7 emergency service, water heater repair, drain cleaning, and professional plumbing solutions. Fast local service. Call now!',
    coordinates: { lat: 37.2935, lng: -80.0548 },
    heroDescription: 'Professional plumbing services throughout Salem and surrounding areas. From emergency repairs to planned installations, we provide expert plumbing solutions for Salem homes and businesses.',
    localProblems: [
      'Water heater failures during cold Salem winters',
      'Sewer line issues from tree roots',
      'Burst pipes from winter freeze',
      'Clogged drains and slow-running fixtures',
      'Water pressure problems in East Salem',
      'Aging plumbing in established Salem homes',
    ],
    whyChooseUs: [
      'Fast response times throughout Salem',
      'Familiar with Salem area homes and plumbing',
      'Available 24/7 for Salem emergencies',
      '16+ years serving Salem residents',
      'Licensed master plumber with local knowledge',
      'Transparent pricing for Salem customers',
    ],
    neighborhoods: [
      'East Salem',
      'West Salem',
      'Salem Heights',
      'College Avenue area',
      'Downtown Salem',
    ],
    serviceHighlights: [
      'Emergency plumbing service',
      'Water heater installation',
      'Drain and sewer cleaning',
      'Leak detection and repair',
      'Fixture installation',
      'Bathroom remodeling plumbing',
      'Sump pump services',
      'Home protection plans',
    ],
    responseTime: 'Average response time in Salem: 40-50 minutes for emergencies',
  },
  'hollins': {
    slug: 'hollins',
    name: 'Hollins',
    state: 'VA',
    h1: 'Emergency Plumbing in Hollins, VA - 24/7 Local Service',
    metaDescription: 'Hollins plumber providing 24/7 emergency service, water heater repair, drain cleaning, and expert plumbing solutions. Fast local response. Call now!',
    coordinates: { lat: 37.3451, lng: -79.9514 },
    heroDescription: 'Reliable plumbing solutions for Hollins residents. Our experienced team provides fast emergency service and quality plumbing work for homes throughout the Hollins community.',
    localProblems: [
      'Well water system issues in rural Hollins areas',
      'Sump pump failures during heavy rain',
      'Septic system plumbing problems',
      'Water heater issues in Hollins homes',
      'Frozen pipes during winter months',
      'Aging plumbing fixtures needing replacement',
    ],
    whyChooseUs: [
      'Experience with Hollins area properties',
      'Well water and septic system knowledge',
      'Fast response to Hollins emergency calls',
      '16+ years serving Hollins residents',
      'Licensed master plumber',
      'Fair, upfront pricing',
    ],
    neighborhoods: [
      'Hollins College area',
      'Route 419 corridor',
      'Plantation Road area',
      'Rural Hollins communities',
    ],
    serviceHighlights: [
      'Emergency plumbing repair',
      'Well water system service',
      'Water heater installation',
      'Sump pump installation and repair',
      'Drain cleaning services',
      'Fixture repairs and replacement',
      'Leak detection',
      'Preventive maintenance',
    ],
    responseTime: 'Average response time in Hollins: 35-45 minutes for emergencies',
  },
  'vinton': {
    slug: 'vinton',
    name: 'Vinton',
    state: 'VA',
    h1: 'Emergency Plumbing in Vinton, VA - 24/7 Fast Response',
    metaDescription: 'Vinton plumber providing 24/7 emergency service, water heater repair, drain cleaning, and professional plumbing for homes and businesses. Call now!',
    coordinates: { lat: 37.2793, lng: -79.8978 },
    heroDescription: 'Fast emergency and scheduled plumbing for Vinton homes and businesses. Expert service for everything from burst pipes to bathroom remodels.',
    localProblems: [
      'Sewer line issues in older Vinton neighborhoods',
      'Water heater failures in Vinton homes',
      'Clogged drains from downtown Vinton properties',
      'Burst pipes during winter freeze',
      'Aging plumbing in Vinton Heights area',
      'Fixture problems in Vinton commercial properties',
    ],
    whyChooseUs: [
      'Fast response throughout Vinton',
      'Familiar with Vinton area plumbing',
      'Available 24/7 for emergencies',
      '16+ years serving Vinton',
      'Licensed master plumber',
      'Commercial and residential expertise',
    ],
    neighborhoods: [
      'Downtown Vinton',
      'Vinton Heights',
      'Washington Avenue area',
      'East Vinton',
      'Route 24 corridor',
    ],
    serviceHighlights: [
      'Emergency plumbing service',
      'Commercial plumbing',
      'Water heater service',
      'Drain and sewer cleaning',
      'Leak detection and repair',
      'Bathroom and kitchen plumbing',
      'Fixture installation',
      'Preventive maintenance plans',
    ],
    responseTime: 'Average response time in Vinton: 35-45 minutes for emergencies',
  },
};

