export interface ServiceContent {
  slug: string;
  title: string;
  h1: string;
  metaDescription: string;
  icon: string;
  heroDescription: string;
  problems: string[];
  solutions: string[];
  process: { step: number; title: string; description: string }[];
  pricingMessage: string;
  expertise: string[];
  relatedServices: string[];
}

export const SERVICE_CONTENT: { [key: string]: ServiceContent } = {
  'emergency-plumbing': {
    slug: 'emergency-plumbing',
    title: 'Emergency Plumbing',
    h1: 'Emergency Plumbing in Cave Spring & Roanoke, VA - 24/7 Fast Response',
    metaDescription: 'Need emergency plumbing? We respond fast 24/7 to burst pipes, overflowing toilets, and water leaks in Cave Spring, Roanoke, Salem, Hollins, and Vinton. Call now!',
    icon: 'emergency',
    heroDescription: 'When disaster strikes at 2 AM, we\'re already on our way. Our emergency plumbing team responds immediately to protect your home from water damage.',
    problems: [
      'Burst pipes causing flooding',
      'Overflowing toilets creating mess',
      'Severe water leaks damaging property',
      'Sewer backups (health hazard)',
      'No water supply to home',
      'Gas line leaks (dangerous)',
      'Water heater failure with flooding',
      'Frozen pipes about to burst',
    ],
    solutions: [
      '24/7 emergency response team',
      'Rapid water shutoff and damage control',
      'Professional pipe repairs and replacements',
      'Emergency drain clearing',
      'Water extraction and cleanup coordination',
      'Gas line emergency shutoff and repair',
      'Temporary fixes to get you through the night',
      'Permanent solutions scheduled promptly',
    ],
    process: [
      {
        step: 1,
        title: 'Call Us Immediately',
        description: 'Reach us 24/7. We answer every emergency call and dispatch immediately.',
      },
      {
        step: 2,
        title: 'Emergency Assessment',
        description: 'We arrive fast, assess the damage, and take immediate action to prevent further issues.',
      },
      {
        step: 3,
        title: 'Rapid Repair',
        description: 'Our master plumber fixes the emergency using professional tools and techniques.',
      },
      {
        step: 4,
        title: 'Damage Prevention',
        description: 'We ensure no further damage occurs and provide guidance on next steps.',
      },
    ],
    pricingMessage: 'Emergency service pricing is transparent and fair. We provide upfront estimates before starting work. No hidden fees, no surprises - just honest emergency plumbing service.',
    expertise: [
      '16+ years handling plumbing emergencies',
      'State licensed master plumber on every emergency call',
      'Fully stocked emergency vehicles',
      'Experience with older Roanoke homes (1950s-1980s)',
      'Fast response times across Cave Spring area',
    ],
    relatedServices: ['leak-detection', 'water-heater-repair-installation', 'drain-cleaning-sewer-services'],
  },
  'water-heater-repair-installation': {
    slug: 'water-heater-repair-installation',
    title: 'Water Heater Repair & Installation',
    h1: 'Water Heater Repair & Installation - Cave Spring & Roanoke, VA',
    metaDescription: 'No hot water? We repair and install water heaters fast. 40-50 gallon tank replacement, expansion tanks, and same-day service in Cave Spring and Roanoke, VA.',
    icon: 'waterHeater',
    heroDescription: 'No hot water? We provide same-day water heater repair and installation services. From simple fixes to complete 40-50 gallon tank replacements.',
    problems: [
      'No hot water in home',
      'Water not hot enough',
      'Water heater making strange noises',
      'Water heater leaking',
      'Rusty or discolored hot water',
      'Hot water runs out quickly',
      'Pilot light won\'t stay lit',
      'High energy bills from old heater',
    ],
    solutions: [
      'Same-day water heater repair',
      '40-50 gallon tank replacement',
      'Expansion tank installation',
      'Tankless water heater installation',
      'Water heater maintenance and flushing',
      'Anode rod replacement',
      'Thermostat adjustment and repair',
      'Emergency water heater shutoff',
    ],
    process: [
      {
        step: 1,
        title: 'Diagnosis',
        description: 'We inspect your water heater to determine if repair or replacement is needed.',
      },
      {
        step: 2,
        title: 'Options & Pricing',
        description: 'We provide clear options with upfront pricing for repair vs. replacement.',
      },
      {
        step: 3,
        title: 'Professional Installation',
        description: 'Expert installation of your new water heater or professional repair of existing unit.',
      },
      {
        step: 4,
        title: 'Testing & Cleanup',
        description: 'We test the system thoroughly and leave your space clean.',
      },
    ],
    pricingMessage: 'Water heater services range from simple repairs to full replacements. We offer competitive pricing on 40-50 gallon tanks and provide detailed estimates before any work begins.',
    expertise: [
      'Experienced with all water heater brands (Taco, Armstrong, Bell and Gossett, Grundfos, Honeywell)',
      'Boiler troubleshooting and installation (Hydronic and steam)',
      'Master licensed Gas fitter',
      'Expansion tank expertise',
      'Energy-efficient recommendations',
    ],
    relatedServices: ['emergency-plumbing', 'leak-detection', 'home-protection-plan'],
  },
  'drain-cleaning-sewer-services': {
    slug: 'drain-cleaning-sewer-services',
    title: 'Drain Cleaning & Sewer Services',
    h1: 'Drain Cleaning & Sewer Services - Cave Spring & Roanoke, VA',
    metaDescription: 'Clogged drains or sewer backup? Professional drain cleaning and sewer services in Cave Spring and Roanoke. Fast relief from clogs and backups.',
    icon: 'drain',
    heroDescription: 'Clogged drains and sewer backups don\'t wait for convenient times. We provide fast, effective drain cleaning and sewer services to restore proper flow.',
    problems: [
      'Slow-draining sinks',
      'Clogged shower or tub drains',
      'Gurgling sounds from drains',
      'Multiple drains backing up',
      'Sewage backing up into home',
      'Foul odors from drains',
      'Standing water in yard',
      'Toilet won\'t flush properly',
    ],
    solutions: [
      'Professional drain snaking',
      'Hydro-jetting for severe clogs',
      'Main sewer line cleaning',
      'Camera inspection to locate problems',
      'Root removal from sewer lines',
      'Preventive drain maintenance',
      'Grease trap cleaning',
      'Emergency sewer backup service',
    ],
    process: [
      {
        step: 1,
        title: 'Problem Assessment',
        description: 'We identify the location and severity of your drain or sewer issue.',
      },
      {
        step: 2,
        title: 'Cleaning Method',
        description: 'We select the appropriate cleaning method - snaking, hydro-jetting, or specialized tools.',
      },
      {
        step: 3,
        title: 'Thorough Cleaning',
        description: 'We clear the blockage completely and ensure proper water flow.',
      },
      {
        step: 4,
        title: 'Prevention Tips',
        description: 'We provide guidance on preventing future clogs and backups.',
      },
    ],
    pricingMessage: 'Drain cleaning services are priced based on the severity and location of the clog. We provide upfront pricing and recommend the most cost-effective solution.',
    expertise: [
      'Professional drain cleaning equipment',
      'Experience with older Roanoke home plumbing',
      'Sewer line expertise',
      'State Backflow Inspector including RPZ\'s',
      '16+ years resolving drain issues',
    ],
    relatedServices: ['emergency-plumbing', 'toilet-fixture-repairs', 'leak-detection'],
  },
  'leak-detection': {
    slug: 'leak-detection',
    title: 'Leak Detection & Repair',
    h1: 'Leak Detection & Repair - Cave Spring & Roanoke, VA',
    metaDescription: 'Water leaks in your home? Expert leak detection and repair services in Cave Spring and Roanoke. Specializing in older homes from 1950s-1980s. Call today!',
    icon: 'leak',
    heroDescription: 'Hidden leaks can cause thousands in damage. Our advanced leak detection services find and fix leaks before they become major problems.',
    problems: [
      'Water stains on ceilings or walls',
      'Unexplained high water bills',
      'Sound of running water when nothing is on',
      'Musty odors or mold growth',
      'Warped flooring or walls',
      'Wet spots in yard',
      'Decreased water pressure',
      'Pipe corrosion in older homes',
    ],
    solutions: [
      'Advanced electronic leak detection',
      'Pipe pressure testing',
      'Slab leak detection',
      'Hidden pipe leak location',
      'Pipe repair and replacement',
      'Repiping for older homes (1950s-1980s)',
      'Pinhole leak repairs',
      'Preventive leak inspections',
    ],
    process: [
      {
        step: 1,
        title: 'Leak Detection',
        description: 'Using advanced equipment, we locate the exact source of the leak.',
      },
      {
        step: 2,
        title: 'Damage Assessment',
        description: 'We assess the extent of water damage and pipe condition.',
      },
      {
        step: 3,
        title: 'Repair Plan',
        description: 'We present repair options from simple fixes to full pipe replacement.',
      },
      {
        step: 4,
        title: 'Expert Repair',
        description: 'Professional repair using quality materials with minimal disruption.',
      },
    ],
    pricingMessage: 'Leak detection and repair pricing depends on leak location and pipe accessibility. We specialize in older Roanoke homes with aging pipes and provide honest assessments.',
    expertise: [
      'Experienced pipe fitter/steam fitter',
      'Specialist in older home plumbing (1950s-1980s Roanoke builds)',
      '16+ years leak detection experience',
      'State licensed master plumber',
      'Minimal invasive repair techniques',
    ],
    relatedServices: ['emergency-plumbing', 'bathroom-kitchen-remodels', 'home-protection-plan'],
  },
  'toilet-fixture-repairs': {
    slug: 'toilet-fixture-repairs',
    title: 'Toilet & Fixture Repairs',
    h1: 'Toilet & Fixture Repairs - Cave Spring & Roanoke, VA',
    metaDescription: 'Toilet repairs, replacements, and faucet changes in Cave Spring and Roanoke. Fast, professional service for all your bathroom and kitchen fixtures.',
    icon: 'toilet',
    heroDescription: 'From running toilets to dripping faucets, we handle all your fixture needs. Professional repairs and replacements with quality parts.',
    problems: [
      'Toilet constantly running',
      'Toilet won\'t flush properly',
      'Toilet leaking at base',
      'Dripping faucets',
      'Low water pressure',
      'Faucet handles hard to turn',
      'Shower valve leaking',
      'Broken fixture hardware',
    ],
    solutions: [
      'Toilet repair and adjustment',
      'Complete toilet replacement',
      'Faucet repair and replacement',
      'Shower and tub fixture repair',
      'Valve replacement',
      'Wax ring replacement',
      'Fixture hardware upgrades',
      'Modern fixture installation',
    ],
    process: [
      {
        step: 1,
        title: 'Fixture Inspection',
        description: 'We inspect your toilet or fixture to determine the best solution.',
      },
      {
        step: 2,
        title: 'Recommendation',
        description: 'We advise whether repair or replacement is more cost-effective.',
      },
      {
        step: 3,
        title: 'Professional Service',
        description: 'Expert installation or repair using quality parts and proper techniques.',
      },
      {
        step: 4,
        title: 'Testing',
        description: 'We test thoroughly to ensure proper function and no leaks.',
      },
    ],
    pricingMessage: 'Fixture repair and replacement services are competitively priced. We provide honest recommendations and use quality parts for lasting results.',
    expertise: [
      'Faucet repair and installation specialist',
      'Toilet repair and replacement expert',
      'All fixture brands and styles',
      '16+ years plumbing experience',
      'Quality parts and warranties',
    ],
    relatedServices: ['bathroom-kitchen-remodels', 'leak-detection', 'drain-cleaning-sewer-services'],
  },
  'bathroom-kitchen-remodels': {
    slug: 'bathroom-kitchen-remodels',
    title: 'Bathroom & Kitchen Remodels',
    h1: 'Bathroom & Kitchen Remodeling Plumbing - Cave Spring & Roanoke, VA',
    metaDescription: 'Expert plumbing for bathroom and kitchen remodels in Cave Spring and Roanoke. Complete plumbing services for your renovation project.',
    icon: 'remodel',
    heroDescription: 'Renovating your bathroom or kitchen? We provide complete plumbing services for your remodel, from rough-in to final fixture installation.',
    problems: [
      'Outdated bathroom fixtures',
      'Kitchen layout doesn\'t work',
      'Need to relocate plumbing',
      'Adding new bathroom',
      'Upgrading to modern fixtures',
      'Aging pipes need replacement',
      'Want water-efficient fixtures',
      'Expanding kitchen or bathroom',
    ],
    solutions: [
      'Complete bathroom plumbing',
      'Kitchen plumbing installation',
      'Pipe relocation and rerouting',
      'Fixture selection guidance',
      'Modern fixture installation',
      'Water line upgrades',
      'Drain line reconfiguration',
      'Collaboration with contractors',
    ],
    process: [
      {
        step: 1,
        title: 'Remodel Planning',
        description: 'We review your remodel plans and provide plumbing layout advice.',
      },
      {
        step: 2,
        title: 'Rough-In Plumbing',
        description: 'We install pipes, drains, and water lines before walls are closed.',
      },
      {
        step: 3,
        title: 'Fixture Installation',
        description: 'Professional installation of sinks, toilets, showers, tubs, and faucets.',
      },
      {
        step: 4,
        title: 'Final Testing',
        description: 'Complete testing to ensure everything works perfectly.',
      },
    ],
    pricingMessage: 'Remodel plumbing is priced based on project scope. We provide detailed estimates and work efficiently to keep your project on schedule.',
    expertise: [
      'Experienced residential and commercial plumbing',
      'Pipe fitter expertise for custom layouts',
      'Modern fixture installation',
      'Code-compliant plumbing',
      'Coordination with remodel contractors',
    ],
    relatedServices: ['toilet-fixture-repairs', 'water-heater-repair-installation', 'leak-detection'],
  },
  'sump-pump-basement-waterproofing': {
    slug: 'sump-pump-basement-waterproofing',
    title: 'Sump Pump & Basement Waterproofing',
    h1: 'Sump Pump Installation & Basement Waterproofing - Cave Spring & Roanoke, VA',
    metaDescription: 'Protect your basement from flooding with professional sump pump installation and waterproofing in Cave Spring and Roanoke. Keep your basement dry!',
    icon: 'sumpPump',
    heroDescription: 'Don\'t let water damage your basement. Professional sump pump installation and basement waterproofing protect your home and belongings.',
    problems: [
      'Water in basement after rain',
      'Sump pump not working',
      'Musty basement odors',
      'Mold growth in basement',
      'Flooding during storms',
      'High water table issues',
      'Basement wall cracks leaking',
      'Inadequate drainage',
    ],
    solutions: [
      'Sump pump installation',
      'Sump pump repair and replacement',
      'Battery backup sump pump systems',
      'Basement waterproofing',
      'French drain installation',
      'Floor drain installation',
      'Pump testing and maintenance',
      'Emergency flood response',
    ],
    process: [
      {
        step: 1,
        title: 'Basement Assessment',
        description: 'We evaluate your basement water issues and recommend solutions.',
      },
      {
        step: 2,
        title: 'System Design',
        description: 'We design a sump pump and waterproofing system for your needs.',
      },
      {
        step: 3,
        title: 'Professional Installation',
        description: 'Expert installation of sump pumps, drains, and waterproofing.',
      },
      {
        step: 4,
        title: 'Testing & Maintenance',
        description: 'Complete testing and maintenance guidance for long-term protection.',
      },
    ],
    pricingMessage: 'Sump pump and waterproofing services are investments in protecting your home. We provide clear pricing and recommend systems that fit your budget and needs.',
    expertise: [
      'Experienced pump installation (Taco, Armstrong, Bell and Gossett, Grundfos, Honeywell)',
      'Residential and commercial pump expert',
      'Basement waterproofing specialist',
      '16+ years protecting homes',
      'Emergency flood response',
    ],
    relatedServices: ['emergency-plumbing', 'leak-detection', 'home-protection-plan'],
  },
  'home-protection-plan': {
    slug: 'home-protection-plan',
    title: 'Home Protection Plan',
    h1: 'Home Protection Plan - Monthly Plumbing Service - Cave Spring & Roanoke, VA',
    metaDescription: 'Monthly plumbing protection plan starting at $19-29/month. Annual inspections, priority service, discounted rates, and peace of mind for your home.',
    icon: 'protection',
    heroDescription: 'Protect your home and save money with our monthly service plan. Preventive maintenance, priority emergency service, and exclusive discounts.',
    problems: [
      'Unexpected plumbing emergencies',
      'High cost of emergency repairs',
      'Lack of regular maintenance',
      'No plumber when you need one',
      'Worry about aging plumbing',
      'Expensive service call fees',
      'Neglected water heater maintenance',
      'Clogged drains from lack of care',
    ],
    solutions: [
      'Monthly service plan ($19-29/month)',
      'Annual plumbing inspection',
      'Priority emergency service',
      'Discounted service rates',
      'Water heater annual flush',
      'Drain line check',
      'Peace of mind protection',
      'Build $1-3k in value monthly',
    ],
    process: [
      {
        step: 1,
        title: 'Sign Up',
        description: 'Choose your plan and enroll for monthly protection.',
      },
      {
        step: 2,
        title: 'Annual Inspection',
        description: 'We perform comprehensive annual plumbing inspection.',
      },
      {
        step: 3,
        title: 'Priority Service',
        description: 'Get priority scheduling for emergencies and service calls.',
      },
      {
        step: 4,
        title: 'Enjoy Savings',
        description: 'Save on all services with your member discount rates.',
      },
    ],
    pricingMessage: 'Home Protection Plans start at just $19-29 per month. This small investment provides major savings and peace of mind for your home\'s plumbing system.',
    expertise: [
      'Preventive maintenance programs',
      '16+ years plumbing experience',
      'Comprehensive inspection protocols',
      'State licensed master plumber',
      'Dedicated member support',
    ],
    relatedServices: ['water-heater-repair-installation', 'drain-cleaning-sewer-services', 'leak-detection'],
  },
};

